export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
export const DELETE_ALL_FLASH_MESSAGES = 'DELETE_ALL_FLASH_MESSAGES';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const ADD_REDIRECT_ROUTE = 'ADD_REDIRECT_ROUTE';
export const CLEAR_REDIRECT_ROUTE = 'CLEAR_REDIRECT_ROUTE';
